### PR TITLE
Add Slovenian language

### PR DESCRIPTION
**Pull request by AdmiralStipe**

### CODE REVIEW

**Comment by milan-fabian** [comment]
@AdmiralStipe the localization files look good, I will try to build a testing version with it today. What name would you like to add to the "thank you" note in the app and documentation?

**Comment by AdmiralStipe** [comment]
> @AdmiralStipe the localization files look good, I will try to build a testing version with it today. What name would you like to add to the "thank you" note in the app and documentation?

I think just @AdmiralStipe will be OK :).

**Comment by AdmiralStipe** [comment]
Just one question, Milan... I'm not really familiar with Github workflows, so I better ask. You wrote, you will prepare a testing version - shall I download it anywhere or will you publish it or send it to me for checking/testing?

**Comment by milan-fabian** [comment]
The testing version was just for confirming that everything is OK. I already merged your pull request, so the localization will be part of the next release of Slideshow (released probably by the end of the next week).
If you want to check the localization in the app before the release, please write to me on milan@slideshow.digital, I can prepare a non-public beta APK for checking.

**Comment by AdmiralStipe** [comment]
Oh, OK, no need for beta from my side, if there will be any errors or changes needed (it's a bit hard to translate some parts, if you don't know the whole context of the string to be translated), I'll just make a new pull request with needed changes for the following releases then. Thx.

**Comment by milan-fabian** [comment]
Slovenian localization has been added in Slideshow version 4.0.3

**Pull request merged**
