### PR TITLE
Spanish translation proposal

### PR DESCRIPTION
**Pull request by TheMrRafus**
I worked in a Spanish translation to Slideshow, I made this pull request to review and change the errors if necessary
Regards
Rafa

### CODE REVIEW

**Review by milan-fabian — COMMENTED** [review]
Hi Rafa, 

Thank you very much for submitting the pull request.
In file spanish.txt I can see that some translations contains additional spaces in formatting, for example after `<b>` tag, or in `% s`. These can cause problem for displaying the translation in Slideshow.
Is it OK if I remove the problematic spaces in a batch, or would you like to review them?

Milan

**Comment by TheMrRafus** [comment]
I can review this
Regards
Rafa

**Comment by TheMrRafus** [comment]
I have reviewed and I think that´s fixed, afterwards if you see any syntax error, feel free to fix it
Regards
Rafa

**Comment by TheMrRafus** [comment]
I think that all the spaces was removed, but if I forgot something, feel free to fix it
You can send me a quick build of the app translated for check the translations?
Regards
Rafa

**Comment by TheMrRafus** [comment]
> 
> 
> I worked in a Spanish translation to Slideshow, I made this pull request to review and change the errors if necessary
> Regards
> Rafa

I fixed all the errors I think, If there are any formatting mistakes, please feel free to fix it
Regards
Rafa

**Comment by milan-fabian** [comment]
I made a small cleanup and merged it, it will be added in the next Slideshow version.

If you find any problem with the translations, feel free to open another merge request.

**Pull request merged**
